title: Paul Hermans
description: Personal website of Paul Hermans, former webhosting provider now in sabbatical.
baseurl: ""
url: "https://paulhermans.eu"
markdown: kramdown

header_pages:
  - about.md
  - blog.md

plugins:
  - jekyll-redirect-from

# Collections for blog posts
#collections:
#  posts:
#    output: true
#    permalink: /blog/:title/
