title: Paul Hermans
description: My personal website
baseurl: ""
url: "https://paulhermans.eu"
markdown: kramdown

header_pages:
  - about.md
  - blog.md

# Collections for blog posts
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
